#This configuration file was written by: org.eclipse.oomph.setup.internal.core.SetupTaskPerformer
#Wed Mar 11 14:02:06 AEDT 2026
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.38.0.20251204-0849
eclipse.p2.data.area=file\:/Users/namandhankhar/.p2/
eclipse.p2.profile=_Users_namandhankhar_eclipse_java-2025-12_Eclipse.app_Contents_Eclipse
eclipse.product=org.eclipse.epp.package.java.product
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.5.700.v20251111-1031.jar@1\:start
osgi.bundles.defaultStartLevel=4
osgi.framework=file\:/Users/namandhankhar/.p2/pool/plugins/org.eclipse.osgi_3.24.0.v20251126-0427.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.3.0.v20251022-1724.jar
osgi.instance.area.default=@user.home/Documents/workspace
osgi.splashPath=file\:/Users/namandhankhar/.p2/pool/plugins/org.eclipse.epp.package.common_4.38.0.20251204-0849
osgi.configuration.cascaded=false
